name: Build & test
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-noetic-ros-base-latest
    steps:
    - uses: ros-tooling/action-ros-ci@0.3.0
      with:
        package-name: rosbag_fancy
        target-ros1-distro: noetic
